[package]
name = "csdl-cot"
version = "0.1.0"
edition = "2024"
authors = ["Mai Dinh Huy", "maidinhhuy.94@gmail.com"]

[dependencies]
memmap2 = "0.7"
arrow-array = "40.0"
arrow-schema = "40.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"